# Generated by Django 5.0.3 on 2024-04-16 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OneByteFood', '0003_alter_reservation_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
